# Generated by Django 4.2.1 on 2023-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField(max_length=12, unique=True, verbose_name='phone')),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
