# Generated by Django 4.2.1 on 2023-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_suggestion_delete_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('short_descriptions', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('price_type', models.CharField(choices=[('сум', 'сум'), ('$', 'USD'), ('UZS', 'UZS')], max_length=5)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='phone_number',
            field=models.IntegerField(max_length=14, unique=True, verbose_name='phone'),
        ),
    ]
