# Generated by Django 4.2.1 on 2023-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_orders_alter_suggestion_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='short_descriptions',
        ),
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_type',
            field=models.CharField(choices=[('сум', 'сум'), ('$', 'USD'), ('UZS', 'UZS')], max_length=3),
        ),
    ]
