# Generated by Django 4.2.1 on 2023-05-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_rename_phone_number_suggestion_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
