# Generated by Django 4.2.1 on 2023-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_orders_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
